# Generated by Django 4.2 on 2025-12-02 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_payment_passenger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='booking',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Passenger',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
