# Generated by Django 4.2 on 2025-12-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_stop'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='travel_datetime',
            field=models.DateTimeField(default='2025-01-01 00:00:00'),
            preserve_default=False,
        ),
    ]
